### ISSUE TITLE
example

### ISSUE THREAD

**Issue by Super-six-java** [ni/easyrdma#18]
Hello, thank you very much for providing this code, but I'm not sure how to use it. Can you provide an example? 
Thank you very much

**Comment by nikhalim** [comment]
Hi, you can try to take a look at some examples here: https://github.com/cgraf78/easyrdma/commit/b1cf019ee24b4450636f38c5eee04a173b007fa0

You can also take a look at the tests and see how the APIs are used (connect, send, etc)

**Comment by Super-six-java** [comment]
thanks very much and i hava another question when i compiler example core Code in ubuntu 22.04. it is success and Generate easyrdma.so Dynamic Link Library.  when   i compiler exampleCode in ubuntu 18.04  ,it`s will error
```
root@ThinkStation-K:~/easyrdma-test-examples/core/build$ cmake ..
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0") found components: system thread filesystem 
-- Configuring done (0.2s)
-- Generating done (0.0s)
-- Build files have been written to: /home/botsc/easyrdma-test-examples/core/build
root@ThinkStation-K:~/easyrdma-test-examples/core/build$ make
[  5%] Building CXX object CMakeFiles/easyrdma.dir/api/errorElaboration.cpp.o
[ 11%] Building CXX object CMakeFiles/easyrdma.dir/api/errorhandling.cpp.o
[ 17%] Building CXX object CMakeFiles/easyrdma.dir/api/rdma_api_c.cpp.o
[ 23%] Building CXX object CMakeFiles/easyrdma.dir/api/rdma_api_common.cpp.o
[ 29%] Building CXX object CMakeFiles/easyrdma.dir/common/RdmaBuffer.cpp.o
[ 35%] Building CXX object CMakeFiles/easyrdma.dir/common/RdmaBufferQueue.cpp.o
[ 41%] Building CXX object CMakeFiles/easyrdma.dir/common/RdmaConnectedSessionBase.cpp.o
[ 47%] Building CXX object CMakeFiles/easyrdma.dir/common/RdmaConnectionData.cpp.o
[ 52%] Building CXX object CMakeFiles/easyrdma.dir/common/RdmaListenerBase.cpp.o
[ 58%] Building CXX object CMakeFiles/easyrdma.dir/common/ThreadUtility.cpp.o
[ 64%] Building CXX object CMakeFiles/easyrdma.dir/linux/RdmaCommon.cpp.o
[ 70%] Building CXX object CMakeFiles/easyrdma.dir/linux/RdmaConnectedSession.cpp.o
[ 76%] Building CXX object CMakeFiles/easyrdma.dir/linux/RdmaConnector.cpp.o
[ 82%] Building CXX object CMakeFiles/easyrdma.dir/linux/RdmaEnumeration.cpp.o
[ 88%] Building CXX object CMakeFiles/easyrdma.dir/linux/RdmaErrorTranslation.cpp.o
/home/botsc/easyrdma-test-examples/core/linux/RdmaErrorTranslation.cpp:46:7: error: ‘IBV_WC_TM_ERR’ was not declared in this scope; did you mean ‘IBV_WC_FATAL_ERR’?
   46 |     { IBV_WC_TM_ERR,              easyrdma_Error_OperatingSystemError       },
      |       ^~~~~~~~~~~~~
      |       IBV_WC_FATAL_ERR
/home/botsc/easyrdma-test-examples/core/linux/RdmaErrorTranslation.cpp:47:7: error: ‘IBV_WC_TM_RNDV_INCOMPLETE’ was not declared in this scope; did you mean ‘IBV_EXP_WC_TM_RNDV_INCOMPLETE’?
   47 |     { IBV_WC_TM_RNDV_INCOMPLETE,  easyrdma_Error_OperatingSystemError       },
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~
      |       IBV_EXP_WC_TM_RNDV_INCOMPLETE
/home/botsc/easyrdma-test-examples/core/linux/RdmaErrorTranslation.cpp:48:1: error: could not convert ‘{{IBV_WC_LOC_LEN_ERR, -734007}, {IBV_WC_LOC_QP_OP_ERR, -734006}, {IBV_WC_LOC_EEC_OP_ERR, -734006}, {IBV_WC_LOC_PROT_ERR, -734006}, {IBV_WC_WR_FLUSH_ERR, -734006}, {IBV_WC_MW_BIND_ERR, -734006}, {IBV_WC_BAD_RESP_ERR, -734006}, {IBV_WC_LOC_ACCESS_ERR, -734006}, {IBV_WC_REM_INV_REQ_ERR, -734006}, {IBV_WC_REM_ACCESS_ERR, -734006}, {IBV_WC_REM_OP_ERR, -734006}, {IBV_WC_RETRY_EXC_ERR, -734006}, {IBV_WC_RNR_RETRY_EXC_ERR, -734006}, {IBV_WC_LOC_RDD_VIOL_ERR, -734006}, {IBV_WC_REM_INV_RD_REQ_ERR, -734006}, {IBV_WC_REM_ABORT_ERR, -734006}, {IBV_WC_INV_EECN_ERR, -734006}, {IBV_WC_INV_EEC_STATE_ERR, -734006}, {IBV_WC_FATAL_ERR, -734006}, {IBV_WC_RESP_TIMEOUT_ERR, -734006}, {IBV_WC_GENERAL_ERR, -734006}, {<expression error>, -734006}, {<expression error>, -734006}}’ from ‘<brace-enclosed initializer list>’ to ‘const std::map<ibv_wc_status, int>’
   48 | };
      | ^
      | |
      | <brace-enclosed initializer list>
CMakeFiles/easyrdma.dir/build.make:271: recipe for target 'CMakeFiles/easyrdma.dir/linux/RdmaErrorTranslation.cpp.o' failed
make[2]: *** [CMakeFiles/easyrdma.dir/linux/RdmaErrorTranslation.cpp.o] Error 1
CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/easyrdma.dir/all' failed
make[1]: *** [CMakeFiles/easyrdma.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2
```

**compiler  env  :      boost 1.74    gcc 11.3.0**

**Comment by ericgross2** [comment]
@Super-six-java you probably need a newer version of libibverbs (part of rdma-core).

**Comment by Super-six-java** [comment]
> thanks very much and i hava another question when i compiler example core Code in ubuntu 22.04. it is success and Generate easyrdma.so Dynamic Link Library. when i compiler exampleCode in ubuntu 18.04 ,it`s will error
> 
> ```
> root@ThinkStation-K:~/easyrdma-test-examples/core/build$ cmake ..
> -- The C compiler identification is GNU 11.3.0
> -- The CXX compiler identification is GNU 11.3.0
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: /usr/bin/cc - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /usr/bin/c++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0") found components: system thread filesystem 
> -- Configuring done (0.2s)
> -- Generating done (0.0s)
> -- Build files have been written to: /home/botsc/easyrdma-test-examples/core/build
> root@ThinkStation-K:~/easyrdma-test-examples/core/build$ make
> [  5%] Building CXX object CMakeFiles/easyrdma.dir/api/errorElaboration.cpp.o
> [ 11%] Building CXX object CMakeFiles/easyrdma.dir/api/errorhandling.cpp.o
> [ 17%] Building CXX object CMakeFiles/easyrdma.dir/api/rdma_api_c.cpp.o
> [ 23%] Building CXX object CMakeFiles/easyrdma.dir/api/rdma_api_common.cpp.o
> [ 29%] Building CXX object CMakeFiles/easyrdma.dir/common/RdmaBuffer.cpp.o
> [ 35%] Building CXX object CMakeFiles/easyrdma.dir/common/RdmaBufferQueue.cpp.o
> [ 41%] Building CXX object CMakeFiles/easyrdma.dir/common/RdmaConnectedSessionBase.cpp.o
> [ 47%] Building CXX object CMakeFiles/easyrdma.dir/common/RdmaConnectionData.cpp.o
> [ 52%] Building CXX object CMakeFiles/easyrdma.dir/common/RdmaListenerBase.cpp.o
> [ 58%] Building CXX object CMakeFiles/easyrdma.dir/common/ThreadUtility.cpp.o
> [ 64%] Building CXX object CMakeFiles/easyrdma.dir/linux/RdmaCommon.cpp.o
> [ 70%] Building CXX object CMakeFiles/easyrdma.dir/linux/RdmaConnectedSession.cpp.o
> [ 76%] Building CXX object CMakeFiles/easyrdma.dir/linux/RdmaConnector.cpp.o
> [ 82%] Building CXX object CMakeFiles/easyrdma.dir/linux/RdmaEnumeration.cpp.o
> [ 88%] Building CXX object CMakeFiles/easyrdma.dir/linux/RdmaErrorTranslation.cpp.o
> /home/botsc/easyrdma-test-examples/core/linux/RdmaErrorTranslation.cpp:46:7: error: ‘IBV_WC_TM_ERR’ was not declared in this scope; did you mean ‘IBV_WC_FATAL_ERR’?
>    46 |     { IBV_WC_TM_ERR,              easyrdma_Error_OperatingSystemError       },
>       |       ^~~~~~~~~~~~~
>       |       IBV_WC_FATAL_ERR
> /home/botsc/easyrdma-test-examples/core/linux/RdmaErrorTranslation.cpp:47:7: error: ‘IBV_WC_TM_RNDV_INCOMPLETE’ was not declared in this scope; did you mean ‘IBV_EXP_WC_TM_RNDV_INCOMPLETE’?
>    47 |     { IBV_WC_TM_RNDV_INCOMPLETE,  easyrdma_Error_OperatingSystemError       },
>       |       ^~~~~~~~~~~~~~~~~~~~~~~~~
>       |       IBV_EXP_WC_TM_RNDV_INCOMPLETE
> /home/botsc/easyrdma-test-examples/core/linux/RdmaErrorTranslation.cpp:48:1: error: could not convert ‘{{IBV_WC_LOC_LEN_ERR, -734007}, {IBV_WC_LOC_QP_OP_ERR, -734006}, {IBV_WC_LOC_EEC_OP_ERR, -734006}, {IBV_WC_LOC_PROT_ERR, -734006}, {IBV_WC_WR_FLUSH_ERR, -734006}, {IBV_WC_MW_BIND_ERR, -734006}, {IBV_WC_BAD_RESP_ERR, -734006}, {IBV_WC_LOC_ACCESS_ERR, -734006}, {IBV_WC_REM_INV_REQ_ERR, -734006}, {IBV_WC_REM_ACCESS_ERR, -734006}, {IBV_WC_REM_OP_ERR, -734006}, {IBV_WC_RETRY_EXC_ERR, -734006}, {IBV_WC_RNR_RETRY_EXC_ERR, -734006}, {IBV_WC_LOC_RDD_VIOL_ERR, -734006}, {IBV_WC_REM_INV_RD_REQ_ERR, -734006}, {IBV_WC_REM_ABORT_ERR, -734006}, {IBV_WC_INV_EECN_ERR, -734006}, {IBV_WC_INV_EEC_STATE_ERR, -734006}, {IBV_WC_FATAL_ERR, -734006}, {IBV_WC_RESP_TIMEOUT_ERR, -734006}, {IBV_WC_GENERAL_ERR, -734006}, {<expression error>, -734006}, {<expression error>, -734006}}’ from ‘<brace-enclosed initializer list>’ to ‘const std::map<ibv_wc_status, int>’
>    48 | };
>       | ^
>       | |
>       | <brace-enclosed initializer list>
> CMakeFiles/easyrdma.dir/build.make:271: recipe for target 'CMakeFiles/easyrdma.dir/linux/RdmaErrorTranslation.cpp.o' failed
> make[2]: *** [CMakeFiles/easyrdma.dir/linux/RdmaErrorTranslation.cpp.o] Error 1
> CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/easyrdma.dir/all' failed
> make[1]: *** [CMakeFiles/easyrdma.dir/all] Error 2
> Makefile:90: recipe for target 'all' failed
> make: *** [all] Error 2
> ```
> 
> **compiler env : boost 1.74 gcc 11.3.0**

i see maybe is my  incard problem  ，ubuntu  22.04 is 100G/s card  ubuntu 18.04 is 40G/s card .and i  note /core/linux/RdmaErrorTranslation.cpp  ：46 、47 rows  ,This can successfully compile。
40G/s card Driver not supported `     // { IBV_WC_TM_ERR,              easyrdma_Error_OperatingSystemError       },
    // { IBV_WC_TM_RNDV_INCOMPLETE,  easyrdma_Error_OperatingSystemError       },`

**Comment by ericgross2** [comment]
@Super-six-java those error codes were added in later versions of libibverbs. You could try commenting out those entries, but you might still run into compatibility issues. It might be better to try building your own copy of rdma-core rather than relying on Ubuntu 18’s old version.

**Comment by Super-six-java** [comment]
[ericgross2](https://github.com/ericgross2) Thank you for your suggestion，i will try 。As you can see my name .I am not very familiar with CPP, although I am learning it, so I may make some low-level mistakes

**Comment by nikhalim** [comment]
Closing this issue since no further action required
