### ISSUE TITLE
win7 X64 run easyrdma_recv.exe and easyrdma_send.exe  Error creating session: -734010   Invalid address.

### ISSUE THREAD

**Issue by Super-six-java** [ni/easyrdma#20]
i have one linux server and one win7 ,  win7_x64 net driver is  MLNX_VPI_WinOF-5_35_All_Win7_x64 and close firewall . linux and win7 can ping each other . when i use nd_rping in win7  Will appear 
![image](https://user-images.githubusercontent.com/55952395/236615169-855dcf4e-2b33-4a7c-b646-34a1b975229c.png) .i`m not sure it`s driver have problem.

when i run  easyrdma_recv.exe or easyrdma_send.exe   ,The console will generate ` Error creating session: -734010   Invalid address.`,but I am sure I have entered the correct address. 
i dont kown `    { (int)(0xC00000CC),            easyrdma_Error_InvalidAddress     }, // STATUS_BAD_NETWORK_NAME from DDK`  In source `easyrdma-add-examples/core/windows/RdmaErrorTranslation.cpp`  38 line

**Comment by nikhalim** [comment]
It does seem like something to do with the Mellanox driver or the network setup itself. I'd encourage you to check with NVIDIA support instead.
